### ISSUE TITLE
error trying to run follow_human.py

### ISSUE THREAD

**Issue by deanh8** [commaai/body-jim#6]
i keep getting this error when trying to run one of the scripts:  do you know what im doing wrong?

"cd /data/openpilot/examples/
python3 follow_human.py 192.168.0.207" 

Traceback (most recent call last):
  File "/usr/local/pyenv/versions/3.11.4/lib/python3.11/site-packages/aiohttp/connector.py", line 992, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
comma@comma-cb3fcb29:/data/openpilot/examples/body-jim/examples$
    raise exceptions[0]
  File "/usr/local/pyenv/versions/3.11.4/lib/python3.11/asyncio/base_events.py", line 1069, in create_connection
    sock = await self._connect_sock(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/pyenv/versions/3.11.4/lib/python3.11/asyncio/base_events.py", line 973, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/pyenv/versions/3.11.4/lib/python3.11/asyncio/selector_events.py", line 634, in sock_connect
    return await fut
           ^^^^^^^^^
  File "/usr/local/pyenv/versions/3.11.4/lib/python3.11/asyncio/selector_events.py", line 674, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('192.168.0.207', 5001)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/openpilot/examples/body-jim/examples/random_walk.py", line 32, in <module>
    run_random_walk(args.body_ip, args.cameras)
  File "/data/openpilot/examples/body-jim/examples/random_walk.py", line 10, in run_random_walk
    env = BodyEnv(body_ip, cameras, [], render_mode="human")
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/pyenv/versions/3.11.4/lib/python3.11/site-packages/bodyjim/env.py", line 36, in __init__
    schema = asyncio.run(client.get_schema(services))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/pyenv/versions/3.11.4/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/pyenv/versions/3.11.4/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/pyenv/versions/3.11.4/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/local/pyenv/versions/3.11.4/lib/python3.11/site-packages/bodyjim/data_stream.py", line 36, in get_schema
    async with session.get(endpoint, params=params) as resp:
  File "/usr/local/pyenv/versions/3.11.4/lib/python3.11/site-packages/aiohttp/client.py", line 1194, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "/usr/local/pyenv/versions/3.11.4/lib/python3.11/site-packages/aiohttp/client.py", line 578, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/pyenv/versions/3.11.4/lib/python3.11/site-packages/aiohttp/connector.py", line 544, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/pyenv/versions/3.11.4/lib/python3.11/site-packages/aiohttp/connector.py", line 911, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/pyenv/versions/3.11.4/lib/python3.11/site-packages/aiohttp/connector.py", line 1235, in _create_direct_connection
    raise last_exc
  File "/usr/local/pyenv/versions/3.11.4/lib/python3.11/site-packages/aiohttp/connector.py", line 1204, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/pyenv/versions/3.11.4/lib/python3.11/site-packages/aiohttp/connector.py", line 1000, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host 192.168.0.207:5001 ssl:default [Connect call failed ('192.168.0.207', 5001)]
comma@comma-cb3fcb29:/data/openpilot/examples/body-jim/examples$
comma@comma-cb3fcb29:/data/openpilot/examples/body-jim/examples$

**Comment by deanh8** [comment]
I also get this error when trying to install the pip 



Collecting bodyjim
  Downloading bodyjim-1.0.1-py3-none-any.whl (9.1 kB)
Collecting teleoprtc>=1.0.1 (from bodyjim)
  Downloading teleoprtc-1.0.1-py3-none-any.whl (8.6 kB)
Collecting aiortc>=1.6.0 (from bodyjim)
  Downloading aiortc-1.8.0-cp38-abi3-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (1.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 3.0 MB/s eta 0:00:00
Collecting aiohttp>=3.7.0 (from bodyjim)
  Downloading aiohttp-3.9.5-cp311-cp311-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (1.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 5.5 MB/s eta 0:00:00
Collecting gymnasium>=0.29.0 (from bodyjim)
  Downloading gymnasium-0.29.1-py3-none-any.whl (953 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 953.9/953.9 kB 6.8 MB/s eta 0:00:00
Collecting numpy>=1.19.0 (from bodyjim)
  Downloading numpy-1.26.4-cp311-cp311-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (14.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.2/14.2 MB 16.1 MB/s eta 0:00:00
Collecting pygame (from bodyjim)
  Downloading pygame-2.5.2-cp311-cp311-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (13.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.6/13.6 MB 17.6 MB/s eta 0:00:00
Collecting aiosignal>=1.1.2 (from aiohttp>=3.7.0->bodyjim)
  Downloading aiosignal-1.3.1-py3-none-any.whl (7.6 kB)
Collecting attrs>=17.3.0 (from aiohttp>=3.7.0->bodyjim)
  Downloading attrs-23.2.0-py3-none-any.whl (60 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.8/60.8 kB 13.2 MB/s eta 0:00:00
Collecting frozenlist>=1.1.1 (from aiohttp>=3.7.0->bodyjim)
  Downloading frozenlist-1.4.1-cp311-cp311-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (273 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 273.3/273.3 kB 33.3 MB/s eta 0:00:00
Collecting multidict<7.0,>=4.5 (from aiohttp>=3.7.0->bodyjim)
  Downloading multidict-6.0.5-cp311-cp311-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (130 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 130.8/130.8 kB 22.4 MB/s eta 0:00:00
Collecting yarl<2.0,>=1.0 (from aiohttp>=3.7.0->bodyjim)
  Downloading yarl-1.9.4-cp311-cp311-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (324 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 324.2/324.2 kB 35.1 MB/s eta 0:00:00
Collecting aioice<1.0.0,>=0.9.0 (from aiortc>=1.6.0->bodyjim)
  Downloading aioice-0.9.0-py3-none-any.whl (24 kB)
Collecting av<12.0.0,>=9.0.0 (from aiortc>=1.6.0->bodyjim)
  Downloading av-11.0.0-cp311-cp311-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (32.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━━━ 19.2/32.0 MB 29.7 MB/s eta 0:00:01ERROR: Could not install packages due to an OSError: [Errno 28] No space left on device

     ━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━ 19.5/32.0 MB 28.6 MB/s eta 0:00:01

**Comment by deanh8** [comment]
I found im having issues with installing it on a VE so  I was doing it the wrong way.. this is the issues Im having that started me down a path of doing it incorrectly..

(venv) PS C:\Users\deanh> pip install bodyjim
Collecting bodyjim
  Using cached bodyjim-1.0.1-py3-none-any.whl.metadata (5.4 kB)
Collecting teleoprtc>=1.0.1 (from bodyjim)
  Using cached teleoprtc-1.0.1-py3-none-any.whl.metadata (2.1 kB)
Collecting aiortc>=1.6.0 (from bodyjim)
  Using cached aiortc-1.8.0-cp38-abi3-win_amd64.whl.metadata (5.6 kB)
Collecting aiohttp>=3.7.0 (from bodyjim)
  Using cached aiohttp-3.9.5-cp312-cp312-win_amd64.whl.metadata (7.7 kB)
Collecting gymnasium>=0.29.0 (from bodyjim)
  Using cached gymnasium-0.29.1-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: numpy>=1.19.0 in c:\users\deanh\venv\lib\site-packages (from bodyjim) (1.26.4)
Requirement already satisfied: pygame in c:\users\deanh\venv\lib\site-packages (from bodyjim) (2.5.2)
Collecting aiosignal>=1.1.2 (from aiohttp>=3.7.0->bodyjim)
  Using cached aiosignal-1.3.1-py3-none-any.whl.metadata (4.0 kB)
Collecting attrs>=17.3.0 (from aiohttp>=3.7.0->bodyjim)
  Using cached attrs-23.2.0-py3-none-any.whl.metadata (9.5 kB)
Collecting frozenlist>=1.1.1 (from aiohttp>=3.7.0->bodyjim)
  Using cached frozenlist-1.4.1-cp312-cp312-win_amd64.whl.metadata (12 kB)
Collecting multidict<7.0,>=4.5 (from aiohttp>=3.7.0->bodyjim)
  Using cached multidict-6.0.5-cp312-cp312-win_amd64.whl.metadata (4.3 kB)
Collecting yarl<2.0,>=1.0 (from aiohttp>=3.7.0->bodyjim)
  Using cached yarl-1.9.4-cp312-cp312-win_amd64.whl.metadata (32 kB)
Collecting aioice<1.0.0,>=0.9.0 (from aiortc>=1.6.0->bodyjim)
  Using cached aioice-0.9.0-py3-none-any.whl.metadata (3.8 kB)
Collecting av<12.0.0,>=9.0.0 (from aiortc>=1.6.0->bodyjim)
  Using cached av-11.0.0-cp312-cp312-win_amd64.whl.metadata (4.7 kB)
Collecting cffi>=1.0.0 (from aiortc>=1.6.0->bodyjim)
  Using cached cffi-1.16.0-cp312-cp312-win_amd64.whl.metadata (1.5 kB)
Collecting cryptography>=42.0.0 (from aiortc>=1.6.0->bodyjim)
  Using cached cryptography-42.0.7-cp39-abi3-win_amd64.whl.metadata (5.4 kB)
Collecting google-crc32c>=1.1 (from aiortc>=1.6.0->bodyjim)
  Using cached google_crc32c-1.5.0-py3-none-any.whl
Collecting pyee>=9.0.0 (from aiortc>=1.6.0->bodyjim)
  Using cached pyee-11.1.0-py3-none-any.whl.metadata (2.8 kB)
Collecting pylibsrtp>=0.10.0 (from aiortc>=1.6.0->bodyjim)
  Using cached pylibsrtp-0.10.0-cp38-abi3-win_amd64.whl.metadata (3.9 kB)
Collecting pyopenssl>=24.0.0 (from aiortc>=1.6.0->bodyjim)
  Using cached pyOpenSSL-24.1.0-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: cloudpickle>=1.2.0 in c:\users\deanh\venv\lib\site-packages (from gymnasium>=0.29.0->bodyjim) (3.0.0)
Collecting typing-extensions>=4.3.0 (from gymnasium>=0.29.0->bodyjim)
  Using cached typing_extensions-4.11.0-py3-none-any.whl.metadata (3.0 kB)
Collecting farama-notifications>=0.0.1 (from gymnasium>=0.29.0->bodyjim)
  Using cached Farama_Notifications-0.0.4-py3-none-any.whl.metadata (558 bytes)
Collecting av<12.0.0,>=9.0.0 (from aiortc>=1.6.0->bodyjim)
  Using cached av-10.0.0.tar.gz (2.4 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [74 lines of output]
      Compiling av\buffer.pyx because it changed.
      [1/1] Cythonizing av\buffer.pyx
      Compiling av\bytesource.pyx because it changed.
      [1/1] Cythonizing av\bytesource.pyx
      Compiling av\descriptor.pyx because it changed.
      [1/1] Cythonizing av\descriptor.pyx
      Compiling av\dictionary.pyx because it changed.
      [1/1] Cythonizing av\dictionary.pyx
      Compiling av\enum.pyx because it changed.
      [1/1] Cythonizing av\enum.pyx
      Compiling av\error.pyx because it changed.
      [1/1] Cythonizing av\error.pyx
      Compiling av\format.pyx because it changed.
      [1/1] Cythonizing av\format.pyx
      Compiling av\frame.pyx because it changed.
      [1/1] Cythonizing av\frame.pyx
      performance hint: av\logging.pyx:232:5: Exception check on 'log_callback' will always require the GIL to be acquired.
      Possible solutions:
          1. Declare 'log_callback' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
          2. Use an 'int' return type on 'log_callback' to allow an error code to be returned.

      Error compiling Cython file:
      ------------------------------------------------------------
      ...
      cdef const char *log_context_name(void *ptr) nogil:
          cdef log_context *obj = <log_context*>ptr
          return obj.name

      cdef lib.AVClass log_class
      log_class.item_name = log_context_name
                            ^
      ------------------------------------------------------------

      av\logging.pyx:216:22: Cannot assign type 'const char *(void *) except? NULL nogil' to 'const char *(*)(void *) noexcept nogil'. Exception values are incompatible. Suggest adding 'noexcept' to the type of 'log_context_name'.

      Error compiling Cython file:
      ------------------------------------------------------------
      ...

      # Start the magic!
      # We allow the user to fully disable the logging system as it will not play
      # nicely with subinterpreters due to FFmpeg-created threads.
      if os.environ.get('PYAV_LOGGING') != 'off':
          lib.av_log_set_callback(log_callback)
                                  ^
      ------------------------------------------------------------

      av\logging.pyx:351:28: Cannot assign type 'void (void *, int, const char *, va_list) except * nogil' to 'av_log_callback' (alias of 'void (*)(void *, int, const char *, va_list) noexcept nogil'). Exception values are incompatible. Suggest adding 'noexcept' to the type of 'log_callback'.
      Compiling av\logging.pyx because it changed.
      [1/1] Cythonizing av\logging.pyx
      Traceback (most recent call last):
        File "C:\Users\deanh\venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\deanh\venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\deanh\venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\deanh\AppData\Local\Temp\pip-build-env-pqygzmli\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\deanh\AppData\Local\Temp\pip-build-env-pqygzmli\overlay\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "C:\Users\deanh\AppData\Local\Temp\pip-build-env-pqygzmli\overlay\Lib\site-packages\setuptools\build_meta.py", line 487, in run_setup
          super().run_setup(setup_script=setup_script)
        File "C:\Users\deanh\AppData\Local\Temp\pip-build-env-pqygzmli\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 157, in <module>
        File "C:\Users\deanh\AppData\Local\Temp\pip-build-env-pqygzmli\overlay\Lib\site-packages\Cython\Build\Dependencies.py", line 1154, in cythonize
          cythonize_one(*args)
        File "C:\Users\deanh\AppData\Local\Temp\pip-build-env-pqygzmli\overlay\Lib\site-packages\Cython\Build\Dependencies.py", line 1321, in cythonize_one
          raise CompileError(None, pyx_file)
      Cython.Compiler.Errors.CompileError: av\logging.pyx
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
(venv) PS C:\Users\deanh>

**Comment by fredyshox** [comment]
It's unclear whether this package works on Windows, and I don't have any Windows machine to test it. I recommend using [WSL](https://learn.microsoft.com/en-us/windows/wsl/install) for now.
